# Generated by Django 6.0.1 on 2026-01-28 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_location', models.CharField(max_length=120)),
                ('to_location', models.CharField(max_length=120)),
                ('ride_date', models.DateField()),
                ('ride_time', models.TimeField()),
                ('vehicle_type', models.CharField(choices=[('car_petrol', 'Petrol Car'), ('bike', 'Bike')], default='car_petrol', max_length=20)),
                ('distance_km', models.FloatField()),
                ('total_seats', models.IntegerField()),
                ('seats_available', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rides_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['ride_date', 'ride_time'],
            },
        ),
        migrations.CreateModel(
            name='RidePassenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='rides.ride')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rides_joined', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Ride Passengers',
                'unique_together': {('user', 'ride')},
            },
        ),
    ]
