# Generated by Django 6.0.1 on 2026-01-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridepassenger',
            name='pickup_notes',
            field=models.TextField(blank=True, help_text='Landmark, timing, or other notes'),
        ),
        migrations.AddField(
            model_name='ridepassenger',
            name='pickup_point',
            field=models.CharField(blank=True, help_text='Pickup location', max_length=200),
        ),
    ]
