# Generated by Django 6.0.1 on 2026-01-30 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0004_livelocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='aadhaar_consent_given',
            field=models.BooleanField(default=False, help_text='User gave explicit consent to verify Aadhaar'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='aadhaar_consent_timestamp',
            field=models.DateTimeField(blank=True, help_text='When user gave consent for Aadhaar verification', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='aadhaar_last_4_digits',
            field=models.CharField(blank=True, help_text='Last 4 digits of Aadhaar (for display only, e.g., XXXX-XXXX-1234)', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='aadhaar_verified',
            field=models.BooleanField(default=False, help_text='Whether Aadhaar has been verified via OTP'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='aadhaar_verified_at',
            field=models.DateTimeField(blank=True, help_text='When Aadhaar was successfully verified', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id_proof_number',
            field=models.CharField(blank=True, help_text='DEPRECATED - Use aadhaar fields instead', max_length=50),
        ),
    ]
