# Generated by Django 6.0.1 on 2026-01-30 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0005_userprofile_aadhaar_consent_given_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='driver_ended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ride',
            name='driver_started',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ride',
            name='passenger_ended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ride',
            name='passenger_started',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ride',
            name='ride_status',
            field=models.CharField(choices=[('created', 'Created'), ('started', 'Started'), ('completed', 'Completed')], default='created', max_length=20),
        ),
    ]
