# Generated by Django 6.0.1 on 2026-01-30 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0006_ride_driver_ended_ride_driver_started_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='vehicle_number',
            field=models.CharField(default='UNKNOWN', help_text='Vehicle registration number (e.g., KL07AB1234)', max_length=15),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(help_text='Phone number must start with 91 and be exactly 12 digits (e.g., 919876543210)', max_length=12),
        ),
    ]
