"""
Django settings for ecocommute project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%a2!c2#+j9*5f4l8u$c9h33)zeie+co9i71oh2)9_y)08(ekey'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rides',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ecocommute.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ecocommute.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Login settings
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'

# Email Configuration
import os

# Use console backend for development/testing (prints emails to console)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# For production with Gmail, uncomment below and set environment variables:
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
# EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
# DEFAULT_FROM_EMAIL = EMAIL_HOST_USER or 'noreply@ecocommute.com'


# ============================================================================
# AADHAAR VERIFICATION SETTINGS
# ============================================================================
# IMPORTANT: Store these credentials in environment variables (.env file)
# NEVER commit API keys to version control (Git)

# Aadhaar API Provider ('cashfree', 'signzy', or 'surepass')
AADHAAR_API_PROVIDER = os.environ.get('AADHAAR_API_PROVIDER', 'cashfree')

# API Credentials (Get from your provider dashboard)
AADHAAR_API_CLIENT_ID = os.environ.get('AADHAAR_API_CLIENT_ID', 'sandbox_client_id')
AADHAAR_API_SECRET_KEY = os.environ.get('AADHAAR_API_SECRET_KEY', 'sandbox_secret_key')

# Sandbox Mode (True for testing, False for production)
AADHAAR_API_SANDBOX = os.environ.get('AADHAAR_API_SANDBOX', 'True') == 'True'

# Use Mock Service (True for local development without real API)
# In mock mode, OTP is always '123456'
AADHAAR_USE_MOCK = os.environ.get('AADHAAR_USE_MOCK', 'True') == 'True'

# COMPLIANCE NOTES:
# - Full Aadhaar numbers are NEVER stored in database
# - Only verification status and last 4 digits are retained
# - All API calls are made server-side only (HTTPS)
# - User consent is mandatory before verification
# - Complies with Aadhaar Act 2016 & DPDP Act 2023
